# Generated by Django 6.0.4 on 2026-04-21 18:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywater',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='dailywater',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_water_per_day'),
        ),
    ]
